### ISSUE TITLE
Safari caches XHR objects retrieved by the client

### ISSUE THREAD

**Issue by jpike88** [joostvunderink/angular-jsonrpc-client#10] opened 2015-12-15 08:12 UTC
This is bad. That total resource size (over 4MB) keeps climbing when it shouldn't after triggering the same requests a couple of times. Some API requests can return a large response, this response should be deleted as a resource, as soon as the promise is returned.

![screen shot 2015-12-15 at 6 11 30 pm](https://cloud.githubusercontent.com/assets/9585787/11805441/4a9f5bd8-a357-11e5-8b83-13050748fed0.png)

![screen shot 2015-12-15 at 6 10 54 pm](https://cloud.githubusercontent.com/assets/9585787/11805434/395d2b48-a357-11e5-869b-695cd67c9aff.png)

**Comment by joostvunderink** [comment] 2015-12-15 09:35
Interesting. I am not sure if this is a problem with the `angular-jsonrpc-client` module, or with the calling code keeping the response object around. Or even with Safari.

What leads you to think that the problem is inside the client? Do you have any ideas on how to fix it?

**Comment by joostvunderink** [comment] 2015-12-15 17:10
Another question: do you have some code that I can run to reproduce this problem?

**Comment by jpike88** [comment] 2015-12-16 00:43
This is something that happens in Safari no matter what you're calling. It's more noticeable if the JSON server is returning data that is in larger amounts of course.

**Comment by joostvunderink** [comment] 2015-12-16 08:52
I have seen the same happening in Chrome. It seems to be happening regardless of whether I have the developer tools open. I don't think there is anything that my module can do differently. If you do, feel free to tell me so I can improve the code!

**Comment by joostvunderink** [comment] 2015-12-23 19:57
Closing this issue as it does not seem to be a problem that's caused by my module. Feel free to reopen with more information if it is a problem with my module after all.

**Closed as completed by joostvunderink** 2015-12-23 19:57 UTC
